### ISSUE TITLE
h264fy is not multiprocess compatible

### ISSUE THREAD

**Issue by palopezv** [erkserkserks/h264ify-firefox#11]
Or at least that is what firefox 49 reports when trying to install the extension in a multiprocess-enabled instance. Now that we are in the transition phase towards multiprocess becoming the default, could you look into it? Thanks.

**Comment by erkserkserks** [comment]
Just added the "multiprocess" flag to package.json. The next version (1.0.5) should be rolling out soon.

**Comment by palopezv** [comment]
Thanks.
