### ISSUE TITLE
As of 2017-05-01 Nightly marks the addon as legacy

### ISSUE THREAD

**Issue by palopezv** [erkserkserks/h264ify-firefox#13]
It means it will stop working when FX 56 comes down the pike. Can you look into how to make this a WebExtension? (My educated guess is that the chrome code is a good start).

(Spookingly, this ended up being issue 13).

**Comment by palopezv** [comment]
Male that FX 57, silly me.

**Comment by eoger** [comment]
Opened an issue on the main repo: https://github.com/erkserkserks/h264ify/issues/29

**Comment by erkserkserks** [comment]
The Firefox extension is now a WebExtension as of v1.0.6!

**Comment by palopezv** [comment]
Very much appreciated!
