### ISSUE TITLE
Add Block 60fps option

### ISSUE THREAD

**Issue by SagaciousZed** [erkserkserks/h264ify-firefox#7]
I found the option to block 60fps video useful in the Chrome version. It would be wonderful to have it for the firefox version.

**Comment by mmazur** [comment]
+1 on this one
When in locations with limited internet availability I can't use 720p because the 60fps version takes too much bandwidth.

**Comment by erkserkserks** [comment]
Okay, adding this as a feature for the next release. I'll have time to poke around later this week, although pull requests are welcome.

**Comment by erkserkserks** [comment]
Version 1.0.4 is up right now and includes an option to disable 60fps video.
