### ISSUE TITLE
Loud static on Raspberry Pi 3

### ISSUE THREAD

**Issue by christopher-dG** [erkserkserks/h264ify-firefox#8]
The add-on helps with the stuttering on videos, but introduces really loud constant static and weird distorted audio on top of it. I'm on a Raspberry Pi 3 with Ubuntu Mate 16.04, I'm assuming the hardware is at least part of the issue.

**Comment by erkserkserks** [comment]
Does this happen with Chrome+h264ify? Does playing this video work correctly on both browsers? http://camendesign.com/code/video_for_everybody/test.html

**Comment by christopher-dG** [comment]
Unfortunately I can't test it on other browsers, since Chrome is not available for ARM and its alternative, Chromium, crashes with a segfault on my system for some reason. The linked video has the same static issue, playing videos locally or online with the extension removed is also no problem.

**Comment by erkserkserks** [comment]
Interesting, the extension should only have an effect on youtube sites. Does the static happen all the time, or only some of the time? The extension essentially makes Firefox play only h.264 videos on youtube, so I would expect your symptoms to occur playing any type of h.264 video in Firefox.

**Comment by AlessandroPorcelli91** [comment]
I can confirm there is loud static under Firefox and not under Chrome, but I doubt that's h264ify's fault. That's probably Firefox's default decoder being rather terrible.
